# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdUfuTBWMyVg6_7I_L-8hzu3I2hEtP1H

#Data Analysis Approach
**Objective**: Analyze our global supply chain performance to understand where we're excelling and where we need improvement.
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv("orders_and_shipments_final_cleaned.csv")
df.head()

df = pd.read_csv("/content/orders_and_shipments_final_cleaned.csv")
df.head()

"""## Initial Business and Supply Chain Metrics Calculation

### Subtask:
Calculate fundamental business metrics such as total sales, average order value, profit margins, and key supply chain metrics like inventory turnover, lead times, and on-time delivery rates, based on the structure of the cleaned data.

"""

total_order_quantity = df["Order Quantity"].sum()
average_order_quantity = df["Order Quantity"].mean()

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Shipment Date"] = pd.to_datetime(df["Shipment Date"])

df["Actual Shipment Days"] = (df["Shipment Date"] - df["Order Date"]).dt.days

average_lead_time = df["Actual Shipment Days"].mean()

df["On-Time Delivery"] = df["Actual Shipment Days"] <= df["Shipment Days - Scheduled"]
percentage_on_time_delivery = df["On-Time Delivery"].mean() * 100

print(f"Total Order Quantity: {total_order_quantity}")
print(f"Average Order Quantity: {average_order_quantity:.2f}")
print(f"Average Actual Shipment Duration (Lead Time): {average_lead_time:.2f} days")
print(f"Percentage of On-Time Deliveries: {percentage_on_time_delivery:.2f}%")

print(
    "\nNote: Total sales, average order value, profit margins, and inventory turnover cannot be accurately calculated without specific price and cost data, which is not available in the current DataFrame."
)

df.columns = (
    df.columns.str.lower()
    .str.replace(r"[^a-z0-9_]", "_", regex=True)
    .str.replace(r"__+", "_", regex=True)
    .str.strip("_")
)

# Dynamically find the column that corresponds to 'Shipment Days - Scheduled Order Date'
# after standardization, by searching for keywords.
scheduled_days_column_candidates = [
    col for col in df.columns if "shipment_days" in col and "scheduled" in col
]

if len(scheduled_days_column_candidates) == 1:
    scheduled_days_column = scheduled_days_column_candidates[0]
elif "shipment_days_scheduled_order_date" in df.columns:
    scheduled_days_column = "shipment_days_scheduled_order_date"
else:
    # Fallback to the most expected name if the search or direct access fails,
    # which implies a deeper issue in standardization or data.
    scheduled_days_column = "shipment_days_scheduled_order_date"

total_order_quantity = df["order_quantity"].sum()
average_order_quantity = df["order_quantity"].mean()

df["order_date"] = pd.to_datetime(df["order_date"])
df["shipment_date"] = pd.to_datetime(df["shipment_date"])

df["actual_shipment_days"] = (df["shipment_date"] - df["order_date"]).dt.days

average_lead_time = df["actual_shipment_days"].mean()

# Extract the numerical scheduled days using the identified column name and a more robust split
# Explicitly convert the column to string type before using .str accessor
df["scheduled_shipment_days_num"] = (
    df[scheduled_days_column]
    .astype(str)
    .str.split(r"\s+", n=1, expand=True)[0]
    .astype(int)
)

df["on_time_delivery"] = df["actual_shipment_days"] <= df["scheduled_shipment_days_num"]
percentage_on_time_delivery = df["on_time_delivery"].mean() * 100

print(f"Total Order Quantity: {total_order_quantity}")
print(f"Average Order Quantity: {average_order_quantity:.2f}")
print(f"Average Actual Shipment Duration (Lead Time): {average_lead_time:.2f} days")
print(f"Percentage of On-Time Deliveries: {percentage_on_time_delivery:.2f}%")

print(
    "\nNote: Total sales, average order value, profit margins, and inventory turnover cannot be accurately calculated without specific price and cost data, which is not available in the current DataFrame."
)

print(df.columns.tolist())

"""## Advanced Analytical Modeling

### Subtask:
Apply appropriate advanced mathematical and statistical techniques, such as regression analysis, time-series forecasting (if applicable), or clustering, to uncover deeper insights and patterns within the data. The specific models will be determined by the characteristics of the data.

**Reasoning**:
To perform advanced analytical modeling as per the instructions, I will first select the specified features, apply one-hot encoding to the categorical features, split the data into training and testing sets, train a RandomForestRegressor model, and then evaluate its performance using MAE and R-squared.
"""


# 1. Select relevant numerical and categorical features
numerical_features = ["order_quantity"]
categorical_features = [
    "shipment_mode",
    "customer_market",
    "customer_region",
    "customer_country",
    "warehouse_country",
]
target = "actual_shipment_days"

X = df[numerical_features + categorical_features]
y = df[target]

# 2. Apply one-hot encoding to the selected categorical features
# Create a column transformer for one-hot encoding
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ],
    remainder="passthrough",  # Keep numerical features as they are
)

# 3. Split the preprocessed data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Train a RandomForestRegressor model
# Create a pipeline that first preprocesses the data and then trains the model
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", RandomForestRegressor(n_estimators=100, random_state=42)),
    ]
)

model.fit(X_train, y_train)

# 5. Evaluate the model's performance on the test set
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r_squared = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"R-squared: {r_squared:.2f}")

"""## Comprehensive Data Visualization

### Subtask:
Create a series of advanced plots and dashboards (e.g., interactive plots, heatmaps, distribution plots, time-series charts with forecasts) to visually represent the findings from both business, supply chain, and advanced analyses, ensuring all plots have clear legends.

"""


# Set a style for better aesthetics
sns.set_style("whitegrid")

# 1. Histogram for 'actual_shipment_days'
plt.figure(figsize=(10, 6))
sns.histplot(df["actual_shipment_days"], kde=True, bins=50)
plt.title("Distribution of Actual Shipment Days")
plt.xlabel("Actual Shipment Days")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# 2. Bar plot for 'percentage_on_time_delivery'
plt.figure(figsize=(8, 5))
plt.bar(["On-Time Delivery"], [percentage_on_time_delivery], color="skyblue")
plt.title("Percentage of On-Time Deliveries")
plt.ylabel("Percentage (%)")
plt.ylim(0, 100)
for i, v in enumerate([percentage_on_time_delivery]):
    plt.text(i, v + 2, f"{v:.2f}%", ha="center", va="bottom")
plt.tight_layout()
plt.show()

# 3. Box plot to show relationship between 'shipment_mode' and 'actual_shipment_days'
plt.figure(figsize=(12, 7))
sns.boxplot(x="shipment_mode", y="actual_shipment_days", data=df)
plt.title("Actual Shipment Days by Shipment Mode")
plt.xlabel("Shipment Mode")
plt.ylabel("Actual Shipment Days")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 4. Scatter plot for 'order_quantity' and 'actual_shipment_days'
plt.figure(figsize=(10, 6))
sns.scatterplot(x="order_quantity", y="actual_shipment_days", data=df, alpha=0.5)
plt.title("Order Quantity vs. Actual Shipment Days")
plt.xlabel("Order Quantity")
plt.ylabel("Actual Shipment Days")
plt.tight_layout()
plt.show()

# 5. Bar plot for average 'actual_shipment_days' for each 'customer_market'
average_shipment_days_by_market = (
    df.groupby("customer_market")["actual_shipment_days"]
    .mean()
    .sort_values(ascending=False)
)
plt.figure(figsize=(12, 7))
sns.barplot(
    x=average_shipment_days_by_market.index,
    y=average_shipment_days_by_market.values,
    palette="viridis",
    hue=average_shipment_days_by_market.index,
    legend=False,
)
plt.title("Average Actual Shipment Days by Customer Market")
plt.xlabel("Customer Market")
plt.ylabel("Average Actual Shipment Days")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# 6. Scatter plot comparing actual vs. predicted 'actual_shipment_days'
plt.figure(figsize=(8, 8))
plt.scatter(y_test, y_pred, alpha=0.3)
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    "r--",
    lw=2,
    label="Perfect Prediction",
)
plt.title("Actual vs. Predicted Actual Shipment Days")
plt.xlabel("Actual Shipment Days")
plt.ylabel("Predicted Shipment Days")
plt.legend()
plt.tight_layout()
plt.show()


# Set a style for better aesthetics
sns.set_style("whitegrid")

# 1. Histogram for 'actual_shipment_days'
plt.figure(figsize=(10, 6))
sns.histplot(df["actual_shipment_days"], kde=True, bins=50)
plt.title("Distribution of Actual Shipment Days")
plt.xlabel("Actual Shipment Days")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# 2. Bar plot for 'percentage_on_time_delivery'
plt.figure(figsize=(8, 5))
plt.bar(["On-Time Delivery"], [percentage_on_time_delivery], color="skyblue")
plt.title("Percentage of On-Time Deliveries")
plt.ylabel("Percentage (%)")
plt.ylim(0, 100)
for i, v in enumerate([percentage_on_time_delivery]):
    plt.text(i, v + 2, f"{v:.2f}%", ha="center", va="bottom")
plt.tight_layout()
plt.show()

# 3. Box plot to show relationship between 'shipment_mode' and 'actual_shipment_days'
plt.figure(figsize=(12, 7))
sns.boxplot(x="shipment_mode", y="actual_shipment_days", data=df)
plt.title("Actual Shipment Days by Shipment Mode")
plt.xlabel("Shipment Mode")
plt.ylabel("Actual Shipment Days")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 4. Scatter plot for 'order_quantity' and 'actual_shipment_days'
plt.figure(figsize=(10, 6))
sns.scatterplot(x="order_quantity", y="actual_shipment_days", data=df, alpha=0.5)
plt.title("Order Quantity vs. Actual Shipment Days")
plt.xlabel("Order Quantity")
plt.ylabel("Actual Shipment Days")
plt.tight_layout()
plt.show()

# 5. Bar plot for average 'actual_shipment_days' for each 'customer_market'
average_shipment_days_by_market = (
    df.groupby("customer_market")["actual_shipment_days"]
    .mean()
    .sort_values(ascending=False)
)
plt.figure(figsize=(12, 7))
sns.barplot(
    x=average_shipment_days_by_market.index,
    y=average_shipment_days_by_market.values,
    palette="viridis",
)
plt.title("Average Actual Shipment Days by Customer Market")
plt.xlabel("Customer Market")
plt.ylabel("Average Actual Shipment Days")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# 6. Scatter plot comparing actual vs. predicted 'actual_shipment_days'
plt.figure(figsize=(8, 8))
plt.scatter(y_test, y_pred, alpha=0.3)
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    "r--",
    lw=2,
    label="Perfect Prediction",
)
plt.title("Actual vs. Predicted Actual Shipment Days")
plt.xlabel("Actual Shipment Days")
plt.ylabel("Predicted Shipment Days")
plt.legend()
plt.tight_layout()
plt.show()

"""## Generate data_analysis.py Script

### Subtask:
Consolidate all the Python code used for data loading, analysis, and visualization into a single, well-documented script named `data_analysis.py` for future use and reference.

"""

# Commented out IPython magic to ensure Python compatibility.
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.metrics import mean_absolute_error, r2_score
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer
# from sklearn.pipeline import Pipeline
#
# # Set a style for better aesthetics in plots
# sns.set_style("whitegrid")
#
# # --- 1. Data Loading ---
# print("--- Data Loading ---")
# df = pd.read_csv('/content/orders_and_shipments_final_cleaned.csv')
# print("Cleaned data loaded successfully. Displaying first 5 rows:")
# print(df.head())
# print("\n")
#
# # --- 2. Column Standardization and Metric Calculation ---
# print("--- Business and Supply Chain Metrics Calculation ---")
# # Standardize column names for easier access
# df.columns = df.columns.str.lower().str.replace(r'[^a-z0-9_]', '_', regex=True).str.replace(r'__+', '_', regex=True).str.strip('_')
#
# # Dynamically find the column that corresponds to 'Shipment Days - Scheduled Order Date'
# scheduled_days_column_candidates = [col for col in df.columns if 'shipment_days' in col and 'scheduled' in col]
#
# if len(scheduled_days_column_candidates) == 1:
#     scheduled_days_column = scheduled_days_column_candidates[0]
# elif 'shipment_days_scheduled_order_date' in df.columns:
#     scheduled_days_column = 'shipment_days_scheduled_order_date'
# else:
#     scheduled_days_column = 'shipment_days_scheduled_order_date'
#
# # Calculate fundamental business and supply chain metrics
# total_order_quantity = df['order_quantity'].sum()
# average_order_quantity = df['order_quantity'].mean()
#
# # Convert date columns to datetime objects
# df['order_date'] = pd.to_datetime(df['order_date'])
# df['shipment_date'] = pd.to_datetime(df['shipment_date'])
#
# # Calculate actual shipment days (lead time)
# df['actual_shipment_days'] = (df['shipment_date'] - df['order_date']).dt.days
# average_lead_time = df['actual_shipment_days'].mean()
#
# # Extract the numerical scheduled days for on-time delivery calculation
# df['scheduled_shipment_days_num'] = df[scheduled_days_column].astype(str).str.split(r'\s+', n=1, expand=True)[0].astype(int)
#
# # Determine on-time deliveries and calculate percentage
# df['on_time_delivery'] = df['actual_shipment_days'] <= df['scheduled_shipment_days_num']
# percentage_on_time_delivery = df['on_time_delivery'].mean() * 100
#
# print(f"Total Order Quantity: {total_order_quantity}")
# print(f"Average Order Quantity: {average_order_quantity:.2f}")
# print(f"Average Actual Shipment Duration (Lead Time): {average_lead_time:.2f} days")
# print(f"Percentage of On-Time Deliveries: {percentage_on_time_delivery:.2f}%")
#
# print("\nNote: Total sales, average order value, profit margins, and inventory turnover cannot be accurately calculated without specific price and cost data, which is not available in the current DataFrame.\n")
#
# # --- 3. Advanced Analytical Modeling ---
# print("--- Advanced Analytical Modeling (RandomForestRegressor) ---")
# # Select relevant numerical and categorical features
# numerical_features = ['order_quantity']
# categorical_features = ['shipment_mode', 'customer_market', 'customer_region', 'customer_country', 'warehouse_country']
# target = 'actual_shipment_days'
#
# X = df[numerical_features + categorical_features]
# y = df[target]
#
# # Apply one-hot encoding to the selected categorical features
# preprocessor = ColumnTransformer(
#     transformers=[
#         ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
#     ],
#     remainder='passthrough' # Keep numerical features as they are
# )
#
# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#
# # Create a pipeline that first preprocesses the data and then trains the model
# model = Pipeline(steps=[('preprocessor', preprocessor),
#                         ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))])
#
# # Train the model
# model.fit(X_train, y_train)
#
# # Evaluate the model's performance on the test set
# y_pred = model.predict(X_test)
#
# mae = mean_absolute_error(y_test, y_pred)
# r_squared = r2_score(y_test, y_pred)
#
# print(f"Mean Absolute Error (MAE): {mae:.2f}")
# print(f"R-squared: {r_squared:.2f}")
# print("\n")
#
# # --- 4. Comprehensive Data Visualization ---
# print("--- Comprehensive Data Visualization ---")
# # 1. Histogram for 'actual_shipment_days'
# plt.figure(figsize=(10, 6))
# sns.histplot(df['actual_shipment_days'], kde=True, bins=50)
# plt.title('Distribution of Actual Shipment Days')
# plt.xlabel('Actual Shipment Days')
# plt.ylabel('Frequency')
# plt.tight_layout()
# plt.show()
#
# # 2. Bar plot for 'percentage_on_time_delivery'
# plt.figure(figsize=(8, 5))
# plt.bar(['On-Time Delivery'], [percentage_on_time_delivery], color='skyblue')
# plt.title('Percentage of On-Time Deliveries')
# plt.ylabel('Percentage (%)')
# plt.ylim(0, 100)
# for i, v in enumerate([percentage_on_time_delivery]):
#     plt.text(i, v + 2, f"{v:.2f}%", ha='center', va='bottom')
# plt.tight_layout()
# plt.show()
#
# # 3. Box plot to show relationship between 'shipment_mode' and 'actual_shipment_days'
# plt.figure(figsize=(12, 7))
# sns.boxplot(x='shipment_mode', y='actual_shipment_days', data=df)
# plt.title('Actual Shipment Days by Shipment Mode')
# plt.xlabel('Shipment Mode')
# plt.ylabel('Actual Shipment Days')
# plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()
#
# # 4. Scatter plot for 'order_quantity' and 'actual_shipment_days'
# plt.figure(figsize=(10, 6))
# sns.scatterplot(x='order_quantity', y='actual_shipment_days', data=df, alpha=0.5)
# plt.title('Order Quantity vs. Actual Shipment Days')
# plt.xlabel('Order Quantity')
# plt.ylabel('Actual Shipment Days')
# plt.tight_layout()
# plt.show()
#
# # 5. Bar plot for average 'actual_shipment_days' for each 'customer_market'
# average_shipment_days_by_market = df.groupby('customer_market')['actual_shipment_days'].mean().sort_values(ascending=False)
# plt.figure(figsize=(12, 7))
# sns.barplot(x=average_shipment_days_by_market.index, y=average_shipment_days_by_market.values, palette='viridis', hue=average_shipment_days_by_market.index, legend=False)
# plt.title('Average Actual Shipment Days by Customer Market')
# plt.xlabel('Customer Market')
# plt.ylabel('Average Actual Shipment Days')
# plt.xticks(rotation=45, ha='right')
# plt.tight_layout()
# plt.show()
#
# # 6. Scatter plot comparing actual vs. predicted 'actual_shipment_days'
# plt.figure(figsize=(8, 8))
# plt.scatter(y_test, y_pred, alpha=0.3)
# plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction')
# plt.title('Actual vs. Predicted Actual Shipment Days')
# plt.xlabel('Actual Shipment Days')
# plt.ylabel('Predicted Shipment Days')
# plt.legend()
# plt.tight_layout()
# plt.show()
